routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\ArticleController;
use App\Http\Controllers\Auth\GoogleSocialiteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function ($router) {
    Route::resource('article', ArticleController::class, ['except' => ['show']]);
    Route::get('/admin', [AdminController::class, 'index'])->name('admin.index');
    Route::post('/admin/update/{user}', [AdminController::class, 'update'])->name('admin.update');
});


Route::get('/article/{article}', [ArticleController::class, 'show'])->name('article.show');

Route::get('auth/google', [GoogleSocialiteController::class, 'redirectToGoogle'])->name('auth.google');
Route::get('google/callback', [GoogleSocialiteController::class, 'handleCallback']);

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;

    public const STATUSES = [
        'draft',
        'under_moderation',
        'published',
        'unpublished',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'title',
        'body',
        'slug',
        'user_id',
        'status'
    ];

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $articles = Article::all();

        return view('article.list', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        $user = Auth::user();
        $statuses = Article::STATUSES;
        if (Gate::allows('isAdmin', $user)) {
            return view('article.create', compact('statuses'));
        }

        $statuses = [$statuses[0], $statuses[3]];
        if (Gate::allows('isCreator', $user)) {
            return view('article.create', compact('statuses'));
        }

        return view('error.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        // Validate posted form data
        $validated = $request->validate([
            'title' => 'required|string|unique:articles|min:5|max:100',
            'body' => 'required|string|min:5|max:2000',
            'status' => 'required|string',
        ]);

        // Create slug from title
        $validated['slug'] = Str::slug($validated['title'], '-');

        // User Id
        $validated['user_id'] = Auth::user()->getAuthIdentifier();

        // Status
        $article = Article::create($validated);

        // Redirect the user to the created post with a success notification
        return redirect(route('article.show', [$article->slug]))->with(
            'notification',
            'Article created!'
        );
    }

    /**
     * Display the specified resource.
     *
     * @param  Article  $article
     * @return Response
     */
    public function show(Article $article)
    {
        // Pass current post to view
        return view('article.show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit(Article $article)
    {
        $user = Auth::user();

        $statuses = Article::STATUSES;
        if (Gate::allows('isAdmin')) {
            return view('article.update', compact('article', 'statuses'));
        }

        if (Gate::allows('isModerator')) {
            return view('article.update', compact('article', 'statuses'));
        }

        // if (!$user->can('update', $article)) {
        //     return view('error.status');
        // }

        $statuses = [$statuses[0], $statuses[3]];
        if (Gate::allows('isCreator') && $user->can('update', $article)) {
            return view('article.update', compact('article', 'statuses'));
        }

        return view('error.edit', compact('user', 'article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Article  $article
     * @return Response
     */
    public function update(Request $request, Article $article)
    {
        // Validate posted form data
        $validated = $request->validate([
            'title' => 'string|min:5|max:100',
            'body' => 'string|min:5|max:2000',
            'status' => 'string',
        ]);
        // Create slug from title
        $validated['slug'] = Str::slug($validated['title'], '-');

        if (
            Gate::allows('isCreator') &&
            $validated['status'] === 'unpublished'
        ) {
            $validated['status'] = 'draft';
        }

        $article->update($validated);
        // Create and save post with validated data

        // Redirect the user to the created post with a success notification
        return redirect(route('article.show', [$article->slug]))->with(
            'notification',
            'Article created!'
        );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy(Article $article)
    {
        // Delete the specified Post
        $article->delete();

        // Redirect user with a deleted notification
        return redirect(route('article.index'))->with(
            'notification',
            '"' . $article->title . '" deleted!'
        );
    }
}

resources/views/article/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <h3>Create</h3>
        </div>
        <div class="row">
            <form method="POST" action="{{ route('article.store') }}">
                @csrf
                <div class="mb-3">
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" class="form-control"
                        value="{{ isset($article) ? $article->title : '' }}" />
                </div>

                <div class="mb-3">
                    <label for="body">Body</label>
                    <textarea name="body" id="body"
                        class="form-control">{{ isset($article) ? $article->body : '' }}</textarea>
                </div>

                <div class="form-group">
                    <label>Select Role</label>
                    <select class="form-control" name="status">
                        @foreach ($statuses as $id => $status)
                            <option value="{{ $status }}" {{ $status == old('status') ? 'selected' : '' }}>
                                {{ $status }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

@endsection

resources/views/article/index.blade.php
@extends('layouts.app')

@section('content')
    <h2>Validated!</h2>
@endsection

resources/views/article/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Title</th>
                        <th scope="col">Body</th>
                        <th scope="col">Status</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($articles as $article)
                        @if(auth()->user()->role === 'creator')
                            @if ($article->status === 'under_moderation')
                                @continue
                            @endif
                            <tr>
                                <td scope="row">
                                    {{ $article->id }}
                                </td>
                                <td>
                                    {{ $article->title }}
                                </td>
                                <td>
                                    {{ strlen($article->body) > 50 ? substr($article->body, 0, 100) . '...' : $article->body }}
                                </td>
                                <td>
                                    {{ $article->status }}
                                </td>
                                <td>
                                    <a href="{{ route('article.edit', $article) }}">Edit</a>
                                </td>
                            </tr>
                        @endif
                            <tr>
                                <td scope="row">
                                    {{ $article->id }}
                                </td>
                                <td>
                                    {{ $article->title }}
                                </td>
                                <td>
                                    {{ strlen($article->body) > 50 ? substr($article->body, 0, 100) . '...' : $article->body }}
                                </td>
                                <td>
                                    {{ $article->status }}
                                </td>
                                <td>
                                    <a href="{{ route('article.edit', $article) }}">Edit</a>
                                </td>
                            </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/article/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>{{ $article->title }}</h1>

            <div>
                <p>
                    {{ $article->body }}
                </p>
            </div>
        </div>
    </div>
@endsection

resources/views/article/update.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <h3>Update</h3>
        </div>
        <div class="row">
            <form method="post" action="{{ route('article.update', $article) }}">
                @csrf
                @method('patch')
                <div class="mb-3">
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" class="form-control"
                        value="{{ isset($article) ? $article->title : '' }}" />
                </div>

                <div class="mb-3">
                    <label for="body">Body</label>
                    <textarea name="body" id="body"
                        class="form-control">{{ isset($article) ? $article->body : '' }}</textarea>
                </div>

                <div class="form-group">
                    <label>Select Role</label>
                    <select class="form-control" name="status">
                        @foreach ($statuses as $id => $status)
                            <option value="{{ $status }}" {{ $status == old('status') ? 'selected' : '' }}>
                                {{ $status }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

@endsection